/**
 * sync-types.mjs
 *
 * Generates Strapi TypeScript types and syncs them to the frontend project.
 *
 * Usage:
 *   node scripts/sync-types.mjs
 *   # or via npm script:
 *   npm run sync-types
 *
 * What it does:
 *   1. Runs `strapi ts:generate-types` to produce types/generated/
 *   2. Writes website/src/types/strapi.ts with all typed interfaces
 */

import { execSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const FRONTEND_ROOT = resolve(ROOT, '..', 'website');
const FRONTEND_TYPES_DIR = resolve(FRONTEND_ROOT, 'src', 'types');

console.log('🔄 Generating Strapi TypeScript types...');

try {
  execSync('npm run strapi -- ts:generate-types', {
    cwd: ROOT,
    stdio: 'inherit',
  });
  console.log('✅ Types generated successfully');
} catch (err) {
  console.error('❌ Failed to generate types:', err.message);
  process.exit(1);
}

if (!existsSync(FRONTEND_TYPES_DIR)) {
  mkdirSync(FRONTEND_TYPES_DIR, { recursive: true });
  console.log(`📁 Created ${FRONTEND_TYPES_DIR}`);
}

const combinedTypes = `/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by: website-backend/scripts/sync-types.mjs
 * Run \`npm run sync-types\` in website-backend to regenerate.
 *
 * These types mirror the Strapi CMS content type schemas.
 * Import from this file to get fully-typed CMS data in the frontend.
 */

// ─────────────────────────────────────────────────────
// Strapi base utility types
// ─────────────────────────────────────────────────────

export interface StrapiMedia {
  id: number;
  documentId: string;
  name: string;
  alternativeText: string | null;
  caption: string | null;
  width: number | null;
  height: number | null;
  formats: {
    thumbnail?: StrapiMediaFormat;
    small?: StrapiMediaFormat;
    medium?: StrapiMediaFormat;
    large?: StrapiMediaFormat;
  } | null;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl: string | null;
  provider: string;
  createdAt: string;
  updatedAt: string;
}

export interface StrapiMediaFormat {
  name: string;
  hash: string;
  ext: string;
  mime: string;
  width: number;
  height: number;
  size: number;
  url: string;
}

export interface StrapiResponse<T> {
  data: T;
  meta: {
    pagination?: {
      page: number;
      pageSize: number;
      pageCount: number;
      total: number;
    };
  };
}

export interface StrapiListResponse<T> {
  data: T[];
  meta: {
    pagination: {
      page: number;
      pageSize: number;
      pageCount: number;
      total: number;
    };
  };
}

export type StrapiBlocks = Array<{
  type: string;
  children?: Array<{ type: string; text?: string; [key: string]: unknown }>;
  [key: string]: unknown;
}>;

// ─────────────────────────────────────────────────────
// Shared components
// ─────────────────────────────────────────────────────

export interface StrapiSEO {
  id: number;
  metaTitle: string;
  metaDescription: string;
  keywords?: string | null;
  metaRobots?: string | null;
  canonicalURL?: string | null;
  structuredData?: Record<string, unknown> | null;
  openGraphTitle?: string | null;
  openGraphDescription?: string | null;
  openGraphImage?: StrapiMedia | null;
  twitterCardType?: 'summary' | 'summary_large_image' | 'app' | 'player';
  twitterTitle?: string | null;
  twitterDescription?: string | null;
  noIndex: boolean;
}

export interface StrapiStat {
  id: number;
  value: string;
  suffix?: string | null;
  label: string;
  description?: string | null;
}

export interface StrapiFeature {
  id: number;
  title: string;
  description?: string | null;
  icon?: string | null;
}

export interface StrapiSocialLink {
  id: number;
  platform: 'instagram' | 'facebook' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok' | 'website' | 'podcast';
  url: string;
  label?: string | null;
}

export interface StrapiCTAButton {
  id: number;
  text: string;
  url: string;
  variant: 'primary' | 'secondary' | 'outline' | 'ghost';
  isExternal: boolean;
}

export interface StrapiNavItem {
  id: number;
  label: string;
  url: string;
  isExternal: boolean;
  order?: number | null;
}

export interface StrapiHeroSection {
  id: number;
  title: string;
  highlightedText?: string | null;
  subtitle?: string | null;
  description?: string | null;
  image?: StrapiMedia | null;
  buttons?: StrapiCTAButton[];
}

/** Single text entry — used for features, tags, credentials, topics, time slots */
export interface StrapiTextItem {
  id: number;
  text: string;
}

export interface StrapiBook {
  id: number;
  title: string;
  description?: string | null;
  coverImage?: StrapiMedia | null;
  purchaseUrl?: string | null;
}

export interface StrapiAward {
  id: number;
  title: string;
  year?: number | null;
  issuer?: string | null;
}

export interface StrapiMediaFeature {
  id: number;
  outlet: string;
  title: string;
  url?: string | null;
  logo?: StrapiMedia | null;
}

export interface StrapiFAQ {
  id: number;
  question: string;
  answer: string;
}

export type StrapiDisabledDayName = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';

export interface StrapiDisabledDay {
  id: number;
  day: StrapiDisabledDayName;
}

// ─────────────────────────────────────────────────────
// Single types
// ─────────────────────────────────────────────────────

export interface StrapiGlobal {
  id: number;
  documentId: string;
  siteName: string;
  siteTagline?: string | null;
  logo?: StrapiMedia | null;
  favicon?: StrapiMedia | null;
  defaultSeo?: StrapiSEO | null;
  socialLinks?: StrapiSocialLink[];
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  googleAnalyticsId?: string | null;
  facebookPixelId?: string | null;
  headerNavigation?: StrapiNavItem[];
  footerNavigation?: StrapiNavItem[];
  footerTagline?: string | null;
  copyrightText?: string | null;
  announcementBar?: string | null;
  announcementBarEnabled: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface StrapiHomepage {
  id: number;
  documentId: string;
  hero?: StrapiHeroSection | null;
  stats?: StrapiStat[];
  whyChooseUsTitle?: string | null;
  whyChooseUsSubtitle?: string | null;
  whyChooseUsFeatures?: StrapiFeature[];
  assuranceTitle?: string | null;
  assuranceSubtitle?: string | null;
  assuranceDescription?: string | null;
  assuranceImage?: StrapiMedia | null;
  assuranceFeatures?: StrapiFeature[];
  servicesShowcaseTitle?: string | null;
  servicesShowcaseSubtitle?: string | null;
  testimonialsTitle?: string | null;
  testimonialsSubtitle?: string | null;
  newsletterTitle?: string | null;
  newsletterSubtitle?: string | null;
  newsletterButtonText?: string | null;
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export interface StrapiAboutPage {
  id: number;
  documentId: string;
  hero?: StrapiHeroSection | null;
  bio?: StrapiBlocks | null;
  profilePhoto?: StrapiMedia | null;
  stats?: StrapiStat[];
  credentialsTitle?: string | null;
  credentials?: StrapiTextItem[];
  booksTitle?: string | null;
  books?: StrapiBook[];
  awardsTitle?: string | null;
  awards?: StrapiAward[];
  mediaFeaturesTitle?: string | null;
  mediaFeatures?: StrapiMediaFeature[];
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaButtons?: StrapiCTAButton[];
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export interface StrapiServicesPage {
  id: number;
  documentId: string;
  hero?: StrapiHeroSection | null;
  introTitle?: string | null;
  introText?: string | null;
  processTitle?: string | null;
  processSteps?: StrapiFeature[];
  faqTitle?: string | null;
  faqs?: StrapiFAQ[];
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaButtons?: StrapiCTAButton[];
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export interface StrapiShopPage {
  id: number;
  documentId: string;
  hero?: StrapiHeroSection | null;
  introTitle?: string | null;
  introText?: string | null;
  guaranteeTitle?: string | null;
  guaranteeDescription?: string | null;
  guaranteeImage?: StrapiMedia | null;
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export interface StrapiContactPage {
  id: number;
  documentId: string;
  hero?: StrapiHeroSection | null;
  officeTitle?: string | null;
  officeAddress?: string | null;
  officePhone?: string | null;
  officeEmail?: string | null;
  officeHours?: string | null;
  mapEmbedUrl?: string | null;
  formTitle?: string | null;
  formSubtitle?: string | null;
  inquiryTopics?: StrapiTextItem[];
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export interface StrapiBookingPage {
  id: number;
  documentId: string;
  hero?: StrapiHeroSection | null;
  introText?: string | null;
  availableTimeSlots?: StrapiTextItem[];
  disabledDays?: StrapiDisabledDay[];
  confirmationTitle?: string | null;
  confirmationMessage?: string | null;
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export interface StrapiBlogPage {
  id: number;
  documentId: string;
  hero?: StrapiHeroSection | null;
  introText?: string | null;
  postsPerPage?: number;
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

// ─────────────────────────────────────────────────────
// Collection types
// ─────────────────────────────────────────────────────

export type StrapiServiceCategory =
  | 'life-coaching'
  | 'executive-coaching'
  | 'group-coaching'
  | 'relationship-coaching'
  | 'speaking'
  | 'workshop'
  | 'online-course';

export interface StrapiService {
  id: number;
  documentId: string;
  title: string;
  slug: string;
  category: StrapiServiceCategory;
  shortDescription: string;
  description?: StrapiBlocks | null;
  price?: number | null;
  priceLabel?: string | null;
  duration?: string | null;
  icon?: string | null;
  image?: StrapiMedia | null;
  features?: StrapiTextItem[];
  isFeatured: boolean;
  order: number;
  sessionType?: string | null;
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export type StrapiProductCategory = 'course' | 'ebook' | 'bundle' | 'resource';

export interface StrapiProduct {
  id: number;
  documentId: string;
  title: string;
  slug: string;
  category: StrapiProductCategory;
  price: number;
  originalPrice?: number | null;
  shortDescription: string;
  description?: StrapiBlocks | null;
  features?: StrapiTextItem[];
  badge?: string | null;
  image?: StrapiMedia | null;
  rating?: number | null;
  studentsCount?: number | null;
  isFeatured: boolean;
  purchaseUrl?: string | null;
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export interface StrapiBlogCategory {
  id: number;
  documentId: string;
  name: string;
  slug: string;
  description?: string | null;
  image?: StrapiMedia | null;
  blogPosts?: StrapiBlogPost[];
  createdAt: string;
  updatedAt: string;
}

export interface StrapiBlogPost {
  id: number;
  documentId: string;
  title: string;
  slug: string;
  excerpt: string;
  content: StrapiBlocks;
  featuredImage?: StrapiMedia | null;
  category?: StrapiBlogCategory | null;
  tags?: StrapiTextItem[];
  readingTimeMinutes?: number | null;
  isFeatured: boolean;
  authorName: string;
  authorBio?: string | null;
  authorPhoto?: StrapiMedia | null;
  relatedPosts?: StrapiBlogPost[];
  seo?: StrapiSEO | null;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export type StrapiTestimonialServiceType =
  | 'life-coaching'
  | 'executive-coaching'
  | 'group-coaching'
  | 'relationship-coaching'
  | 'speaking'
  | 'workshop'
  | 'online-course'
  | 'general';

export interface StrapiTestimonial {
  id: number;
  documentId: string;
  clientName: string;
  clientTitle?: string | null;
  clientCompany?: string | null;
  quote: string;
  rating: number;
  avatar?: StrapiMedia | null;
  serviceType: StrapiTestimonialServiceType;
  isFeatured: boolean;
  order: number;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export interface StrapiTeamMember {
  id: number;
  documentId: string;
  name: string;
  title: string;
  bio?: string | null;
  photo?: StrapiMedia | null;
  socialLinks?: StrapiSocialLink[];
  order: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  publishedAt?: string | null;
}

export type StrapiBookingStatus = 'pending' | 'payment_pending' | 'confirmed' | 'cancelled' | 'completed' | 'no-show';

export interface StrapiBookingSubmission {
  id: number;
  documentId: string;
  name: string;
  email: string;
  phone?: string | null;
  sessionType: string;
  preferredDate?: string | null;
  preferredTime?: string | null;
  goals?: string | null;
  notes?: string | null;
  status: StrapiBookingStatus;
  customer?: StrapiCustomer | null;
  reference?: number | null;
  internalNotes?: string | null;
  createdAt: string;
  updatedAt: string;
}

export type StrapiContactStatus = 'new' | 'read' | 'replied' | 'archived';

export interface StrapiContactSubmission {
  id: number;
  documentId: string;
  firstName: string;
  lastName?: string | null;
  email: string;
  phone?: string | null;
  topic: string;
  message: string;
  status: StrapiContactStatus;
  reference?: number | null;
  internalNotes?: string | null;
  createdAt: string;
  updatedAt: string;
}

export type StrapiSubscriberStatus = 'subscribed' | 'unsubscribed' | 'bounced';
export type StrapiSubscriberSource = 'homepage' | 'blog' | 'shop' | 'booking' | 'contact' | 'popup' | 'other';

export interface StrapiNewsletterSubscriber {
  id: number;
  documentId: string;
  email: string;
  firstName?: string | null;
  status: StrapiSubscriberStatus;
  source: StrapiSubscriberSource;
  unsubscribedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

// ─────────────────────────────────────────────────────
// Orders & customers
// ─────────────────────────────────────────────────────

export interface StrapiOrderItem {
  id: number;
  productTitle: string;
  productSlug?: string | null;
  unitPrice: number;
  quantity: number;
  lineTotal: number;
  product?: StrapiProduct | null;
}

export type StrapiOrderStatus = 'pending' | 'paid' | 'failed' | 'refunded' | 'cancelled';
export type StrapiOrderPaymentType = 'product' | 'booking-deposit';

export interface StrapiOrder {
  id: number;
  documentId: string;
  customer?: StrapiCustomer | null;
  customerName?: string | null;
  customerEmail?: string | null;
  customerPhone?: string | null;
  items?: StrapiOrderItem[];
  subtotal?: number | null;
  total?: number | null;
  status: StrapiOrderStatus;
  paymentType: StrapiOrderPaymentType;
  bookingSubmission?: StrapiBookingSubmission | null;
  createdAt: string;
  updatedAt: string;
}

export interface StrapiCustomer {
  id: number;
  documentId: string;
  firstName?: string | null;
  lastName?: string | null;
  email: string;
  phone?: string | null;
  orders?: StrapiOrder[];
  bookings?: StrapiBookingSubmission[];
  isVIP: boolean;
  tags?: StrapiTextItem[];
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

// ─────────────────────────────────────────────────────
// Utility helpers
// ─────────────────────────────────────────────────────

/** Extract plain string array from a StrapiTextItem component list */
export function extractTextItems(items: StrapiTextItem[] | undefined | null): string[] {
  return items?.map(i => i.text) ?? [];
}

/** Map StrapiDisabledDay names to JS day-of-week numbers (0 = Sunday) */
export function disabledDaysToNumbers(days: StrapiDisabledDay[] | undefined | null): number[] {
  const map: Record<StrapiDisabledDayName, number> = {
    Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3,
    Thursday: 4, Friday: 5, Saturday: 6,
  };
  return days?.map(d => map[d.day]) ?? [];
}
`;

const FRONTEND_TYPES_OUTPUT = resolve(FRONTEND_TYPES_DIR, 'strapi.ts');
writeFileSync(FRONTEND_TYPES_OUTPUT, combinedTypes, 'utf-8');
console.log(`✅ Types synced to ${FRONTEND_TYPES_OUTPUT}`);

console.log('\n🎉 Done! Import types in your frontend like:');
console.log("   import type { StrapiService, StrapiProduct } from '@/types/strapi';");
console.log("   import { extractTextItems, disabledDaysToNumbers } from '@/types/strapi';");
